// Simple PDF export using browser's print functionality
// For a production app, you might want to use a library like jsPDF or html2pdf

export type NoteExportData = {
  title: string
  content: string
  videoTitle?: string
  playlistTitle?: string
  createdAt?: string
  timestamps?: { time: string; note: string }[]
}

export function exportNotesToPDF(data: NoteExportData) {
  // Create a new window for printing
  const printWindow = window.open("", "_blank")
  if (!printWindow) {
    alert("Please allow popups to export PDF")
    return
  }

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${data.title} - Notes</title>
        <style>
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #1a1a1a;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
          }
          .header {
            border-bottom: 2px solid #e5e5e5;
            padding-bottom: 20px;
            margin-bottom: 30px;
          }
          .header h1 {
            font-size: 28px;
            margin-bottom: 8px;
          }
          .header .meta {
            color: #666;
            font-size: 14px;
          }
          .content {
            white-space: pre-wrap;
          }
          .content h1 { font-size: 24px; margin: 24px 0 16px; }
          .content h2 { font-size: 20px; margin: 20px 0 12px; }
          .content h3 { font-size: 18px; margin: 16px 0 8px; }
          .content p { margin-bottom: 16px; }
          .content ul, .content ol { margin: 16px 0; padding-left: 24px; }
          .content li { margin-bottom: 8px; }
          .content code {
            background: #f5f5f5;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'Monaco', 'Menlo', monospace;
            font-size: 14px;
          }
          .content pre {
            background: #f5f5f5;
            padding: 16px;
            border-radius: 8px;
            overflow-x: auto;
            margin: 16px 0;
          }
          .content blockquote {
            border-left: 4px solid #e5e5e5;
            padding-left: 16px;
            margin: 16px 0;
            color: #666;
            font-style: italic;
          }
          .timestamps {
            margin-top: 40px;
            border-top: 2px solid #e5e5e5;
            padding-top: 20px;
          }
          .timestamps h2 {
            font-size: 18px;
            margin-bottom: 16px;
          }
          .timestamp-item {
            display: flex;
            gap: 16px;
            padding: 8px 0;
            border-bottom: 1px solid #f0f0f0;
          }
          .timestamp-time {
            font-family: 'Monaco', 'Menlo', monospace;
            color: #666;
            font-size: 14px;
            min-width: 60px;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e5e5;
            color: #999;
            font-size: 12px;
            text-align: center;
          }
          @media print {
            body { padding: 20px; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${escapeHtml(data.title)}</h1>
          <div class="meta">
            ${data.videoTitle ? `Video: ${escapeHtml(data.videoTitle)}<br>` : ""}
            ${data.playlistTitle ? `Playlist: ${escapeHtml(data.playlistTitle)}<br>` : ""}
            ${data.createdAt ? `Exported: ${new Date(data.createdAt).toLocaleDateString()}` : `Exported: ${new Date().toLocaleDateString()}`}
          </div>
        </div>
        
        <div class="content">
          ${convertMarkdownToHtml(data.content)}
        </div>
        
        ${data.timestamps && data.timestamps.length > 0 ? `
          <div class="timestamps">
            <h2>Bookmarked Timestamps</h2>
            ${data.timestamps.map(t => `
              <div class="timestamp-item">
                <span class="timestamp-time">${t.time}</span>
                <span>${escapeHtml(t.note)}</span>
              </div>
            `).join("")}
          </div>
        ` : ""}
        
        <div class="footer">
          Generated by FlowTube
        </div>
        
        <script>
          window.onload = function() {
            window.print();
          }
        </script>
      </body>
    </html>
  `

  printWindow.document.write(html)
  printWindow.document.close()
}

function escapeHtml(text: string): string {
  const div = document.createElement("div")
  div.textContent = text
  return div.innerHTML
}

function convertMarkdownToHtml(markdown: string): string {
  if (!markdown) return ""
  
  let html = escapeHtml(markdown)
  
  // Headers
  html = html.replace(/^### (.*$)/gm, "<h3>$1</h3>")
  html = html.replace(/^## (.*$)/gm, "<h2>$1</h2>")
  html = html.replace(/^# (.*$)/gm, "<h1>$1</h1>")
  
  // Bold and italic
  html = html.replace(/\*\*\*(.*?)\*\*\*/g, "<strong><em>$1</em></strong>")
  html = html.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
  html = html.replace(/\*(.*?)\*/g, "<em>$1</em>")
  
  // Code blocks
  html = html.replace(/```([\s\S]*?)```/g, "<pre><code>$1</code></pre>")
  html = html.replace(/`(.*?)`/g, "<code>$1</code>")
  
  // Blockquotes
  html = html.replace(/^&gt; (.*$)/gm, "<blockquote>$1</blockquote>")
  
  // Lists
  html = html.replace(/^\* (.*$)/gm, "<li>$1</li>")
  html = html.replace(/^- (.*$)/gm, "<li>$1</li>")
  html = html.replace(/(<li>.*<\/li>)/s, "<ul>$1</ul>")
  
  // Paragraphs
  html = html.replace(/\n\n/g, "</p><p>")
  html = "<p>" + html + "</p>"
  
  // Clean up empty paragraphs
  html = html.replace(/<p><\/p>/g, "")
  html = html.replace(/<p>(<h[1-6]>)/g, "$1")
  html = html.replace(/(<\/h[1-6]>)<\/p>/g, "$1")
  
  return html
}
